### ISSUE TITLE
FriendlyLianDan(更友好的炼丹体验) 在2022.3.28更新后已失效

### ISSUE THREAD

**Issue by dragonslayer431** [shabbywu/GameMod#12]
https://bbs.3dmgame.com/thread-6262471-1-1.html
涉及到了炼丹ui的变化，因此dll失效了。
理论山影响应该包括稳定版和测试版。测试版确认失效（之前有效）
如果能修复，不胜感谢。。
个人对这种dll的debug实在无能。。

**Comment by shabbywu** [comment]
以为等下次更稳定版再修..结果憋了好几次更新都是测试版的. 今晚有空就看看

**Comment by shabbywu** [comment]
@rottenapple11 fixed
