### ISSUE TITLE
[觅长生]看到药草能显示能作为哪个丹药的材料就好了

### ISSUE THREAD

**Issue by majorcheng** [shabbywu/GameMod#4]
有目的的去npc身上扫货

**Comment by shabbywu** [comment]
太多了...展示不了的

**Comment by shabbywu** [comment]
@majorcheng 

新写的一个 Mod

FriendlyLianDan(更友好的炼丹体验)
- 炼丹界面中展示 Hover 中的丹药的功效
- 自动计算所有炼丹丹方
- 仅展示可炼制的丹方
- 丹方按药草的价值排序


用一下就会知道一个药草可以被多少个丹药炼制...

因为炼丹只看主药和副药的属性能不能符合丹方的需求，然后再看药引能不能中和药性, 
所以, 在不讨论药量的前提下, 一种草药可以炼所有药性符合的丹药.

我写了这个丹方生成的 Mod, 理论上可以做这个功能，但是预估的数量很多, 不太好展示.

**Comment by shabbywu** [comment]
update, 简单写了个发现还行.
![image](https://user-images.githubusercontent.com/5237578/151311385-b5145b28-00b4-4954-a198-626f12682194.png)

![image](https://user-images.githubusercontent.com/5237578/151311462-01bf83e0-b948-4286-9722-a4fe06e9f042.png)

**Comment by shabbywu** [comment]
https://github.com/shabbywu/GameMod/releases/download/v20220127/BetterTooltips.dll
