### ISSUE TITLE
FriendlyLianDan功能建议

### ISSUE THREAD

**Issue by sherlockHlb** [shabbywu/GameMod#5]
是否能加个限制,
否则药材太多的情况下.
打开丹炉会卡死

**Comment by shabbywu** [comment]
卡顿有2个方面的可能:
1. 第一次枚举丹方时需要动态计算
2. 展示太多可能的丹方, 每个丹方都有多个 GameObject, 会引起 unity 的资源消耗, 而且那个滚动条还不是动态加载的, 越多就越卡


所以, 可能的优化方向也有2个:
1. 限制药材数量(这个在配置里有了)
2. 限制每个丹药展示的丹方总量(这个还没有)


我目前能想到的点是这些，看看你还有没有其他想法呢？

**Comment by sherlockHlb** [comment]
所以我是想添加一个,比如限制每个丹药展示的丹方总量这个就很好.
还有显示全体单方实际并不能全部.比如
![8F9%1EHS7QYC8P @R@465}V](https://user-images.githubusercontent.com/30238046/153137034-49bb69d4-bbf5-4749-a687-01de52f902cb.png)
这个,我实际已经学会,但是单方里并没有出现

**Comment by sherlockHlb** [comment]
或者可以将每次动态载入改为静态计算,然后每次读取.
但是这样要改动代码过大了

**Comment by shabbywu** [comment]
> 所以我是想添加一个,比如限制每个丹药展示的丹方总量这个就很好. 还有显示全体单方实际并不能全部.比如 ![8F9%1EHS7QYC8P @R@465}V](https://user-images.githubusercontent.com/30238046/153137034-49bb69d4-bbf5-4749-a687-01de52f902cb.png) 这个,我实际已经学会,但是单方里并没有出现



![image](https://user-images.githubusercontent.com/5237578/153225067-3d138f7c-9709-4089-b0aa-4c7b12ee0f6b.png)

这个是有的, 如果你开启了【仅展示可炼制的丹方】然后又不够药材的话，就会被过滤掉.

p.s. 这个选项也是用来优化性能的...

![image](https://user-images.githubusercontent.com/5237578/153225120-ee3b5ca5-1e99-4257-9fb5-540058c15d37.png)

**Comment by sherlockHlb** [comment]
药材是充足的.
这界面是啥!

**Comment by sherlockHlb** [comment]
材料是充足的,并且可以制作的.
看第二张图
但是就是没有这个配方
![image](https://user-images.githubusercontent.com/30238046/153239803-2a9a2a2d-fb61-420a-872f-57d2e6ec76f8.png)
材料是充足的,但是左边并未出现该单方

**Comment by sherlockHlb** [comment]
![image](https://user-images.githubusercontent.com/30238046/153240264-8d7c20c5-aa94-4c6a-8a02-7630b915ac3a.png)
![image](https://user-images.githubusercontent.com/30238046/153240445-0f3fbff4-c762-469e-9863-778dd1718018.png)
以及通过next添加的单方也不会显示

**Comment by shabbywu** [comment]
刚埋点测试了下性能, 是由于丹方过多, 导致创建 GameObject 和判断丹方是否可合成 这两个地方消耗了太多资源。

做了丹方的延迟加载，现在开屏不会卡顿了，过段时间再发个版本，最近比较忙。

**Comment by shabbywu** [comment]
next 的丹方不展示是因为我直接用的官方数据源:
- Effect/json/d_LianDan.py.DanFangBiao.json
- Effect/json/d_items.py.datas.json

next 是修改了内存里的对象, 需要看看他最终加载到哪里, 才可以做兼容

**Comment by shabbywu** [comment]
![image](https://user-images.githubusercontent.com/5237578/153250292-974fb85a-fa78-40a2-b110-cb60c3f2eaf7.png)

emmm, 不清楚你还用了哪些 Mod, 我这里丹方都是正常展示的.

你贴一下你的配置吧.  BepInEx\config\cn.shabywu.michangsheng.FriendlyLianDan.cfg

**Comment by sherlockHlb** [comment]
```
## Settings file was created by plugin 更友好的炼丹 v0.1.0
## Plugin GUID: cn.shabywu.michangsheng.FriendlyLianDan

[DanFangGenerator]

## 生成所有药性符合的丹方
# Setting type: Boolean
# Default value: true
GenerateAllDanFang = true

## 丹方生成器最大的药草数量
# Setting type: Int32
# Default value: 12
MaxHerbsNum = 9

[DanFangHelper]

## 仅展示可炼制的丹方
# Setting type: Boolean
# Default value: true
OnlyShowProductable = true

## 丹方根据药草的成本排序
# Setting type: Boolean
# Default value: true
OrderByHerbsCost = false


```

**Comment by sherlockHlb** [comment]
如果能只计算自己已经拥有的单方项下就比较合理了.
这样也不会让"单方"物品失去存在意义.

**Comment by sherlockHlb** [comment]
失踪的是五品丹药_道源丹,不是天尘丹.

![image](https://user-images.githubusercontent.com/30238046/153268779-e8a8da80-3476-4649-83ef-f46c6953e924.png)
刚才配图有错

**Comment by sherlockHlb** [comment]
还少一个长生丹.
![image](https://user-images.githubusercontent.com/30238046/153269124-febc690d-ce44-40f2-bcbb-271543be706c.png)
六品的少
天元神丹\天道源丹\太乙碧莹丹等弹药
![觅长生_86sHQzLjcn](https://user-images.githubusercontent.com/30238046/153270062-ae7343b0-44a2-4c42-8935-2cbe6aedb3bd.png)
![fTZA7CrjVn](https://user-images.githubusercontent.com/30238046/153270084-f5f7c006-a639-44ca-a127-03cfedd47afe.png)

![觅长生_ILQtZmHP46](https://user-images.githubusercontent.com/30238046/153270037-26510d7d-7440-42d6-8b50-8108cfb8f39b.png)
![觅长生_S3bsEn6agE](https://user-images.githubusercontent.com/30238046/153270051-859b38cb-1b27-4501-a6a2-af98992f415b.png)

**Comment by sherlockHlb** [comment]
关掉生成全部单方的情况下,
又能找到这些单方(已经学习的情况下)

**Comment by sherlockHlb** [comment]
找到问题了,为了避免卡顿,设置计算数量过低.
导致无法计算出单方,所以没有显示出单方
道源丹需要的最少素材是10
我一般设置为9
所以无法计算出

**Comment by sherlockHlb** [comment]
还是我.这个配方,原配方13个材料,算不出来.
但是可以用9材料的替代,还是算不出来
![image](https://user-images.githubusercontent.com/30238046/153290105-c55afa34-a7e8-4517-b927-4e83daf499c2.png)
![image](https://user-images.githubusercontent.com/30238046/153290119-206a2d84-d637-483a-930e-8e75b4478b0f.png)
![image](https://user-images.githubusercontent.com/30238046/153290133-fc2b50ff-a18f-46a4-bce2-66743e4a6c5a.png)

**Comment by sherlockHlb** [comment]
大哥你先发吧.
已经卡的受不了
每次炼药都要先卡半分钟

**Comment by sherlockHlb** [comment]
还是要限制生成的配方数量才行,一个单方几百种配方...
资源开销太大

**Comment by sherlockHlb** [comment]
以及青冥丹的问题还是存在,无法显示更简单的配方

**Comment by shabbywu** [comment]
@sherlockHlb 最新版调整了数据源, 如果还在玩的话可以看看有木有改善这个问题。issue 先 close 了
