### ISSUE TITLE
[bug]BetterTooltips

### ISSUE THREAD

**Issue by sherlockHlb** [shabbywu/GameMod#7]
![9TKC8 DI {G5X0 P1(U0F@Y](https://user-images.githubusercontent.com/30238046/153545555-004966f5-0491-40db-8c38-c96084fc6ac3.png)
![71L`C7H}$60@8_WQ2LBUME7](https://user-images.githubusercontent.com/30238046/153545570-252d374a-3afa-4686-b650-6214daecddee.png)
显示两次,且取消ShowYaoYin = false无效

**Comment by shabbywu** [comment]
和另一个 Mod 冲突了, 不知道另一个 Mod 是怎样实现的, 等下次游戏有大更新后再统一跟进

**Comment by shabbywu** [comment]
简单修了一个版本. 在 release 里可以下载最新的.
