### ISSUE TITLE
[Suggestion] ShoterLearnTime(缩短学习时间)

### ISSUE THREAD

**Issue by ndrwln** [shabbywu/GameMod#9]
Make learn time scale off of comprehension. ie. make comprehension (悟道) a better stat.

悟道 -> 缩短学习时间

**Comment by shabbywu** [comment]
😭我看不懂大兄弟在说什么, 如果是中国人我们直接说中文...如果是外国友人我们讲点简单的词汇...

---

I'm not good at English, please using simple words. Thanks!

**Comment by ndrwln** [comment]
xD 我是个外国人，没有多少中文知识。

我希望悟性能够更好。让它更多地 影响/缩短 学习时间。
I want comprehension to be better. Make it affect/shorten learning time more.

↑ 悟性, ↑ 缩短学习时间

**Comment by ndrwln** [comment]
![Help](https://user-images.githubusercontent.com/46463074/157582013-b92b6248-6ac0-4951-8dfe-a769c19501b4.png)

**Comment by Cherrysaber** [comment]
good idea.I will do it soon.I want to know how to play 修仙 game without enough chinese knowledge.

**Comment by Cherrysaber** [comment]
> Make learn time scale off of comprehension. ie. make comprehension (悟道) a better stat.
> 
> 悟道 -> 缩短学习时间

https://github.com/Cherrysaber/GameMod/tree/main/michangsheng/ShoterLearnTime
It work as you wish.You can adjust the ratio by edit ShorterBaseWuXin and ShorterNeedWuxin in config file

**Comment by shabbywu** [comment]
@ndrwln 

It's a good ieda to make comprehension(悟性) better impact to 领悟/突破功法.

So i implement this ieda with a math function called "Logistic". 

With this function, this Mod can provide a smooth function on comprehension and learning efficiency,
![image](https://user-images.githubusercontent.com/5237578/158879853-001a19e7-ae4c-4b81-a968-3e7faa6a59d0.png)
(X axis is comprehension(悟性), and Y axis is the % of learn time reduction, 20% is a constant set to not affect balance to much )

I'm not sure if this implement is what you expect, but I think this change is also interesting.


You can find the new mod at https://github.com/shabbywu/GameMod/releases/tag/v20220318

**Comment by Cherrysaber** [comment]
> @ndrwln
> 
> It's a good ieda to make comprehension(悟性) better impact to 领悟/突破功法.
> 
> So i implement this ieda with a math function called "Logistic".
> 
> With this function, this Mod can provide a smooth function on comprehension and learning efficiency, ![image](https://user-images.githubusercontent.com/5237578/158879853-001a19e7-ae4c-4b81-a968-3e7faa6a59d0.png) (X axis is comprehension(悟性), and Y axis is the % of learn time reduction, 20% is a constant set to not affect balance to much )
> 
> I'm not sure if this implement is what you expect, but I think this change is also interesting.
> 
> You can find the new mod at https://github.com/shabbywu/GameMod/releases/tag/v20220318

我觉得可以把境界加进来，高境界突破低境界功法，大幅度减少耗时。金丹/元婴/化神 减少 白/蓝/紫 功法学习时间

**Comment by shabbywu** [comment]
已实现提案, 另一个提案可列入参考范围.
